# RustFlow Configuration for stdout output

# HTTP metrics server address
metrics_addr: "127.0.0.1:8081"

# Collector configurations (using different ports to avoid conflicts)
collectors:
  netflow: "0.0.0.0:9996"

# Logging configuration
logging:
  level: "info"  # debug, info, warn, error
  structured: true

# Output configuration - stdout
output:
  format: "json"  # json, binary, text
  producer: "raw"  # raw, proto
  transport: "file"  # file, kafka
  # No file_path specified = output to stdout
  kafka:
    brokers:
      - "localhost:9092"
    topic: "netflow"
    key: null

# Performance configuration
performance:
  buffer_size: 9000
  worker_threads: 4
  batch_size: 1000 